version: "3.7"
services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - service-db:/var/lib/postgresql/data
    networks:
      - service-net

  app:
    build: .
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - service-net
  admin:
    image: nicolaka/netshoot
    networks:
      - service-net

volumes:
  service-db:

networks:
  service-net:
    driver: bridge
