version: "3.7"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:app
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - service-db:/foo

volumes:
  service-db:
